# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_profile_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='owner_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
