# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20161021_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internship',
            old_name='description01',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='workexperience',
            old_name='description',
            new_name='description01',
        ),
        migrations.RemoveField(
            model_name='internship',
            name='description02',
        ),
        migrations.AddField(
            model_name='workexperience',
            name='description02',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
