# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 21:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_1', models.CharField(blank=True, max_length=500, null=True)),
                ('body_2', models.CharField(blank=True, max_length=500, null=True)),
                ('user_experience', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_development', models.CharField(blank=True, max_length=50, null=True)),
                ('training_session', models.CharField(blank=True, max_length=50, null=True)),
                ('fun', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
